services:
  postgres:
    image: postgres:17-alpine
    container_name: email-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - email-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  email-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: email-backend
    environment:
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - DEBUG=${DEBUG}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_V1_STR=${API_V1_STR}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy  
    networks:
      - email-network

  email-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: email-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    networks:
      - email-network
    depends_on:
      - email-api

volumes:
  postgres_data:

networks:
  email-network:
    driver: bridge